version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
jobs:
  single-job-lifecycle:
    executor: terraform/default
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TF_TOKEN_app_terraform_io\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.3.4
      - terraform/fmt:
          path: .
      - terraform/validate:
          path: .
      - terraform/init:
          backend: true
          backend_config_file: backend.hcl
          path: .
      - terraform/plan:
          backend_config_file: backend.hcl
          path: .
      - terraform/apply:
          backend_config_file: backend.hcl
          path: .
      - terraform/destroy:
          path: .
    working_directory: ~/src
workflows:
  single-job-lifecycle:
    jobs:
      - single-job-lifecycle
