orbs:
  terraform: frameio/terraform@0.15.0
version: 2.1
workflows:
  plan:
    jobs:
      - terraform/init:
          filters:
            branches:
              only:
                - main
      - terraform/plan:
          requires:
            - terraform/init
      - approval:
          requires:
            - terraform/plan
          type: approval
      - terraform/apply:
          requires:
            - approval
