version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            pwd
            ls
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
#      - plan-destroy:
#          requires:
#            - apply
#      - hold-destroy:
#          type: approval
#          requires:
#            - plan-destroy
#      - destroy:
#          requires:
#            - hold-destroy

#version: '2.1'
#orbs:
#  terraform: circleci/terraform@3.1
#jobs:
#  single-job-lifecycle:
#    executor: terraform/default
#    steps:
#      - checkout
#      - run:
#          command: >-
#            echo "credentials \"app.terraform.io\" {token =
#            \"$TF_TOKEN_app_terraform_io\"}" > $HOME/.terraformrc
#          name: Create .terraformrc file locally
#      - terraform/install:
#          arch: amd64
#          os: linux
#          terraform_version: latest
#      - terraform/fmt:
#          path: .
#      - terraform/validate:
#          path: .
#      - terraform/init:
#          backend: true
#          backend_config_file: backend.hcl
#          path: .
#      - terraform/plan:
#          backend_config_file: backend.hcl
#          path: .
#      - terraform/apply:
#          backend_config_file: backend.hcl
#          path: .
#      - terraform/destroy:
#          path: .
#    working_directory: ~/src
#workflows:
#  single-job-lifecycle:
#    jobs:
#      - single-job-lifecycle
